#define JL_POWERKEY_PRESS                                  "JLOG0"
#define JL_USBCHARGING_START                               "JLOG1"
#define JL_USBCHARGING_END                                 "JLOG2"
#define JL_NEWRINGING_CONNECTION                           "JLOG3"
#define JL_INCOMINGCALL_RINGING                            "JLOG4"
#define JL_PMS_WAKEFULNESS_ASLEEP                          "JLOG5"
#define JL_PMS_WAKEFULNESS_DREAMING                        "JLOG6"
#define JL_PMS_WAKEFULNESS_NAPPING                         "JLOG7"
#define JL_PMS_WAKEUP_FINISHED                             "JLOG8"
#define JL_POWERKEY_RELEASE                                "JLOG9"
#define JL_KERNEL_LCD_OPEN                                 "JLOG10"
#define JL_KERNEL_LCD_SUSPEND                              "JLOG11"
#define JL_KERNEL_LCD_POWER_ON                             "JLOG12"
#define JL_KERNEL_LCD_POWER_OFF                            "JLOG13"
#define JL_KERNEL_PM_SUSPEND_WAKEUP                        "JLOG14"
#define JL_GO_TO_SLEEP_REASON_USER                         "JLOG15"
#define JL_KERNEL_PM_SUSPEND_SLEEP                         "JLOG16"
#define JL_KERNEL_PM_DEEPSLEEP_WAKEUP                      "JLOG17"
#define JL_KERNEL_LCD_RESUME                               "JLOG18"
#define JL_SYSPROC_INIT_POWERON_START                      "JLOG19"
#define JL_SYSPROC_INIT_POWERON_END                        "JLOG20"
#define JL_SERVICEMANAGER_POWERON_START                    "JLOG21"
#define JL_SERVICEMANAGER_STARTUP                          "JLOG22"
#define JL_START_SYSTEMSERVER                              "JLOG23"
#define JL_LAUNCHER_STARTUP                                "JLOG24"
#define JL_ZYGOTE_START                                    "JLOG25"
#define JL_FIRST_BOOT                                      "JLOG26"
#define JL_BOOT_PROGRESS_START                             "JLOG27"
#define JL_BOOT_PROGRESS_PRELOAD_START                     "JLOG28"
#define JL_BOOT_PROGRESS_PRELOAD_END                       "JLOG29"
#define JL_BOOT_PROGRESS_SYSTEM_RUN                        "JLOG30"
#define JL_BOOT_PROGRESS_PMS_START                         "JLOG31"
#define JL_BOOT_PROGRESS_PMS_READY                         "JLOG32"
#define JL_BOOT_PROGRESS_AMS_READY                         "JLOG33"
#define JL_BOOT_PROGRESS_ENABLE_SCREEN                     "JLOG34"
#define JL_PROXIMITY_SENSOR_FAR                            "JLOG35"
#define JL_PROXIMITY_SENSOR_NEAR                           "JLOG36"
#define JL_JANK_FRAME_SKIP                                 "JLOG37"
#define JL_JANK_FRAME_INFLATE_TIME                         "JLOG38"
#define JL_JANK_FRAME_OBTAIN_TIME                          "JLOG39"
#define JL_JANK_FRAME_SETUP_TIME                           "JLOG40"
#define JL_JANK_FRAME_COMPOSE_TIME                         "JLOG41"
#define JL_SLIDE_TO_CLICK                                  "JLOG42"
#define JL_APP_LAUNCHING_BEGIN                             "JLOG43"
#define JL_APP_LAUNCHING_END                               "JLOG44"
#define JL_COVER_WAKE_LOCK                                 "JLOG45"
#define JL_BOOT_PROGRESS_INITZYGOTE_START                  "JLOG46"
#define JL_RIL_RESPONSE_NEW_SMS                            "JLOG47"
#define JL_DISPATCH_NORMAL_SMS                             "JLOG48"
#define JL_SEND_BROADCAST_SMS                              "JLOG49"
#define JL_DISPATCH_SMS_FAILED                             "JLOG50"
#define JL_WAP_DISPATCH_PDU                                "JLOG51"
#define JL_TP_GESTURE_KEY                                  "JLOG52"
#define JL_WAKEUP_DBCLICK                                  "JLOG53"
#define JL_INPUTDISPATCH_FINGERPRINT                       "JLOG54"
#define JL_FINGER_INDENTIFY_OK                             "JLOG55"
#define JL_FINGER_INDENTIFY_FAILED                         "JLOG56"
#define JL_ROTATION_CHANGED                                "JLOG57"
#define JL_START_ROTATION_ANIM                             "JLOG58"
#define JL_END_ROTATION_ANIM                               "JLOG59"

#define JLID_POWERKEY_PRESS                                   0
#define JLID_USBCHARGING_START                                1
#define JLID_USBCHARGING_END                                  2
#define JLID_NEWRINGING_CONNECTION                            3
#define JLID_INCOMINGCALL_RINGING                             4
#define JLID_PMS_WAKEFULNESS_ASLEEP                           5
#define JLID_PMS_WAKEFULNESS_DREAMING                         6
#define JLID_PMS_WAKEFULNESS_NAPPING                          7
#define JLID_PMS_WAKEUP_FINISHED                              8
#define JLID_POWERKEY_RELEASE                                 9
#define JLID_KERNEL_LCD_OPEN                                  10
#define JLID_KERNEL_LCD_SUSPEND                               11
#define JLID_KERNEL_LCD_POWER_ON                              12
#define JLID_KERNEL_LCD_POWER_OFF                             13
#define JLID_KERNEL_PM_SUSPEND_WAKEUP                         14
#define JLID_GO_TO_SLEEP_REASON_USER                          15
#define JLID_KERNEL_PM_SUSPEND_SLEEP                          16
#define JLID_KERNEL_PM_DEEPSLEEP_WAKEUP                       17
#define JLID_KERNEL_LCD_RESUME                                18
#define JLID_SYSPROC_INIT_POWERON_START                       19
#define JLID_SYSPROC_INIT_POWERON_END                         20
#define JLID_SERVICEMANAGER_POWERON_START                     21
#define JLID_SERVICEMANAGER_STARTUP                           22
#define JLID_START_SYSTEMSERVER                               23
#define JLID_LAUNCHER_STARTUP                                 24
#define JLID_ZYGOTE_START                                     25
#define JLID_FIRST_BOOT                                       26
#define JLID_BOOT_PROGRESS_START                              27
#define JLID_BOOT_PROGRESS_PRELOAD_START                      28
#define JLID_BOOT_PROGRESS_PRELOAD_END                        29
#define JLID_BOOT_PROGRESS_SYSTEM_RUN                         30
#define JLID_BOOT_PROGRESS_PMS_START                          31
#define JLID_BOOT_PROGRESS_PMS_READY                          32
#define JLID_BOOT_PROGRESS_AMS_READY                          33
#define JLID_BOOT_PROGRESS_ENABLE_SCREEN                      34
#define JLID_PROXIMITY_SENSOR_FAR                             35
#define JLID_PROXIMITY_SENSOR_NEAR                            36
#define JLID_JANK_FRAME_SKIP                                  37
#define JLID_JANK_FRAME_INFLATE_TIME                          38
#define JLID_JANK_FRAME_OBTAIN_TIME                           39
#define JLID_JANK_FRAME_SETUP_TIME                            40
#define JLID_JANK_FRAME_COMPOSE_TIME                          41
#define JLID_SLIDE_TO_CLICK                                   42
#define JLID_APP_LAUNCHING_BEGIN                              43
#define JLID_APP_LAUNCHING_END                                44
#define JLID_COVER_WAKE_LOCK                                  45
#define JLID_BOOT_PROGRESS_INITZYGOTE_START                   46
#define JLID_RIL_RESPONSE_NEW_SMS                             47
#define JLID_DISPATCH_NORMAL_SMS                              48
#define JLID_SEND_BROADCAST_SMS                               49
#define JLID_DISPATCH_SMS_FAILED                              50
#define JLID_WAP_DISPATCH_PDU                                 51
#define JLID_TP_GESTURE_KEY                                   52
#define JLID_WAKEUP_DBCLICK                                   53
#define JLID_INPUTDISPATCH_FINGERPRINT                        54
#define JLID_FINGER_INDENTIFY_OK                              55
#define JLID_FINGER_INDENTIFY_FAILED                          56
#define JLID_ROTATION_CHANGED                                 57
#define JLID_START_ROTATION_ANIM                              58
#define JLID_END_ROTATION_ANIM                                59
