#=============================================================================
#=============================================================================

#obj-y += hsad/

obj-$(CONFIG_INPUTHUB) += inputhub/
obj-$(CONFIG_LOGGER_EXTEND) += log/
obj-$(CONFIG_BCMGPS) += gps/
obj-$(CONFIG_HUAWEI_TS) += touchscreen/
obj-$(CONFIG_BCMDHD) += wifi/
obj-y += nfc/
obj-$(CONFIG_HUAWEI_TP_COLOR_INFO) += tp_color/
obj-y += sensor/
obj-$(CONFIG_MAXQ616_POWER_SWITCH) += irda/
obj-$(CONFIG_HUAWEI_KSTATE) += hw_kstate/
obj-$(CONFIG_HUAWEI_DSM) += dsm/
obj-y += ext_modem/
obj-$(CONFIG_TFA9887) += tfa9887/
obj-y += ap_cp/